version: '3'

services:

  npm:
    image: node:10
    volumes:
      - ./app:/app
    working_dir: /app
    user: node
    entrypoint: [npm]
    command: [install]

  expo:
    image: node:10
    volumes:
      - ./app:/app
    working_dir: /app
    user: node
    entrypoint: [expo]
