AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Parameters:

  Environment:
    Type: String
    AllowedValues:
      - development
      - production
      - staging
      - testing

  EventName:
    Type: String
    Default: CONCERT_LAUSANNE_2019


Resources:

  UserPool:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: users/cloudformation.yml
      Parameters:
        Environment: !Ref Environment
        EventName: !Ref EventName
      Tags:
        - Key: component
          Value: user-pool

  LausanneConcert:
    Type: AWS::Serverless::Application
    Properties:
      Location: concert/cloudformation.yml
      Parameters:
        AdminUserPoolGroupName: !GetAtt UserPool.Outputs.AdminUserPoolGroupName
        CognitoUserPoolId: !GetAtt UserPool.Outputs.CognitoUserPoolId
        Environment: !Ref Environment
        EventName: !Ref EventName
      Tags:
        - Key: component
          Value: concert


Outputs:

  ConcertWebSocketURI:
    Value: !GetAtt LausanneConcert.Outputs.WebSocketURI

  CognitoUserPoolId:
    Value: !GetAtt UserPool.Outputs.CognitoUserPoolId

  MobileUserPoolClientId:
    Value: !GetAtt UserPool.Outputs.MobileUserPoolClientId
