export const CHOICE_COLOR = 'CHOICE_COLOR';
export const CHOICE_EMOTION_ANGER = 'CHOICE_EMOTION_ANGER';
export const CHOICE_EMOTION_HAPPINESS = 'CHOICE_EMOTION_HAPPINESS';

export default {
  CHOICE_COLOR,
  CHOICE_EMOTION_ANGER,
  CHOICE_EMOTION_HAPPINESS,
};
