export const CHOICE_CHILLS = 'CHOICE_CHILLS';
export const CHOICE_COLOR = 'CHOICE_COLOR';
export const CHOICE_EMOTION_ENERGY = 'CHOICE_EMOTION_ENERGY';
export const CHOICE_EMOTION_HAPPINESS = 'CHOICE_EMOTION_HAPPINESS';
export const CHOICE_MENTAL_IMAGERY = 'CHOICE_MENTAL_IMAGERY';
