export const STAGE_CHOICE_CHILLS = 'STAGE_CHOICE_CHILLS';
export const STAGE_CHOICE_IMAGERY = 'STAGE_CHOICE_IMAGERY';
export const STAGE_CHOICE_SYNESTHESIA = 'STAGE_CHOICE_SYNESTHESIA';
export const STAGE_END = 'STAGE_END';
export const STAGE_WAITING = 'STAGE_WAITING';
