ATTR_RECORD_TYPE = "recordType"
ATTR_RECORD_ID = "recordId"

ATTR_CHOICE_TIMESTAMP = "timestamp"
ATTR_CHOICE_TYPE = "choiceType"
ATTR_CHOICE_VALUE_CHILLS = "chills"
ATTR_CHOICE_VALUE_COLOR = "colors"
ATTR_CHOICE_VALUE_EMOTION = "emotions"
ATTR_CHOICE_VALUE_IMAGERY = "imagery"

ATTR_CONNECTION_STACK_NAME = "stackName"

CHOICE_CHILLS = "CHOICE_CHILLS"
CHOICE_COLOR = "CHOICE_COLOR"
CHOICE_EMOTION = "CHOICE_EMOTION"
CHOICE_IMAGERY = "CHOICE_IMAGERY"

RECORD_TYPE_AGGREGATE = "AGGREGATE"
RECORD_TYPE_CHOICE = "CHOICE"
RECORD_TYPE_CONNECTION = "CONNECTION"
