ATTR_RECORD_TYPE = "record_type"
ATTR_RECORD_ID = "record_id"

ATTR_RECORD_STACK_NAME = "stack_name"

RECORD_TYPE_AGGREGATE = "AGGREGATE"
RECORD_TYPE_CHOICES = "CHOICES"
RECORD_TYPE_CONNECTION = "CONNECTION"
