ATTR_RECORD_ID = "recordId"
ATTR_CREATED_AT = "createdAt"
ATTR_AGGREGATE_TOTAL_CHOICES = "choices"

ATTR_CHOICE_TIMESTAMP = "timestamp"
ATTR_CHOICE_TYPE = "choiceType"
ATTR_CHOICE_VALUE_CHILLS = "chills"
ATTR_CHOICE_VALUE_COLOR = "colors"
ATTR_CHOICE_VALUE_EMOTION = "emotions"
ATTR_CHOICE_VALUE_EMOTION_TYPE = "emotionType"
ATTR_CHOICE_VALUE_IMAGERY = "imagery"

ATTR_CONNECTION_LAMBDA_MAPPING_UUID = "lambdaMappingUuid"
ATTR_CONNECTION_SNS_SUBSCRIPTION_ARNS = "snsSubscriptionArns"
ATTR_CONNECTION_SQS_QUEUE_URL = "sqsQueueUrl"

CHOICE_CHILLS = "CHOICE_CHILLS"
CHOICE_COLOR = "CHOICE_COLOR"
CHOICE_EMOTION_ENERGY = "CHOICE_EMOTION_ENERGY"
CHOICE_EMOTION_HAPPINESS = "CHOICE_EMOTION_HAPPINESS"
CHOICE_IMAGERY = "CHOICE_IMAGERY"

RECORD_ID_AGGREGATE = "AGGREGATE"
RECORD_ID_EVENT_STAGE = "EVENT_STAGE"

RECORD_ID_PREFIX_CHOICE = "CHOICE"
RECORD_ID_PREFIX_CONNECTION = "CONN"
