version: 2.1

orbs:
  github-wiki: sjawhar/github-wiki@0.3.0


jobs:
  lambdas-test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: cd concert && ./test.sh

  lambdas-lint:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: cd concert/app && pipenv install --dev && pipenv run lint

  cloudformation-validate:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install --user awscli==1.16.35
      - run:
          name: Validate CloudFormation template
          command: PATH="~/.local/bin:${PATH}" ./validate-templates.sh

  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install --user aws-sam-cli==0.17.0 awscli==1.16.192
      - run:
          name: Validate CloudFormation template
          command: PATH="~/.local/bin:${PATH}" ./deploy.sh development us-east-1


workflows:
  test-and-deploy:
    jobs:
      # - lambdas-test
      - lambdas-lint
      - cloudformation-validate
      - deploy:
          requires:
            - lambdas-lint
            # - lambdas-test
            - cloudformation-validate
      - github-wiki/build-and-deploy:
          commit-user-email: circleci@enchanted-brain
          sidebar-placeholder: '{{SIDEBAR_GENERATE}}'
          ssh-key-fingerprint: 42:38:62:83:7e:81:3e:5f:b1:9c:5f:72:b3:78:9a:bc
          filters:
            branches:
              only: master
