version: 2.1

orbs:
  github-wiki: sjawhar/github-wiki@0.3.0


jobs:
  client-install:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "client/app/package-lock.json" }}
      - run: cd client/app && npm ci
      - save_cache:
          paths:
            - /home/circleci/.npm
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "client/app/package-lock.json" }}
      - persist_to_workspace:
          root: client/app
          paths:
            - node_modules

  client-lint:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - attach_workspace:
          at: client/app
      - run: cd client/app && npm run lint

  client-test:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - attach_workspace:
          at: client/app
      - run: cd client/app && npm run test

  lambdas-test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: cd concert && ./test.sh

  lambdas-lint:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: cd concert/app && pipenv install --dev && pipenv run lint

  cloudformation-validate:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install --user awscli==1.16.35
      - run:
          name: Validate CloudFormation template
          command: PATH="~/.local/bin:${PATH}" ./validate-templates.sh

  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install --user aws-sam-cli==0.17.0 awscli==1.16.192
      - run:
          name: Validate CloudFormation template
          command: PATH="~/.local/bin:${PATH}" ./deploy.sh development us-east-1


workflows:
  test-and-deploy:
    jobs:
      - client-install
      - client-lint:
          requires:
            - client-install
      - client-test:
          requires:
            - client-install
      - lambdas-test
      - lambdas-lint
      - cloudformation-validate
      - deploy:
          requires:
            - client-lint
            - client-test
            - lambdas-lint
            - lambdas-test
            - cloudformation-validate
          filters:
            branches:
              only: master
      - github-wiki/build-and-deploy:
          name: deploy-wiki
          commit-user-email: circleci@enchanted-brain
          sidebar-placeholder: '{{SIDEBAR_GENERATE}}'
          ssh-key-fingerprint: 42:38:62:83:7e:81:3e:5f:b1:9c:5f:72:b3:78:9a:bc
          filters:
            branches:
              only: master
