AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Parameters:

  Environment:
    Type: String
    AllowedValues:
      - development
      - production
      - staging
      - testing

  ValidChoiceTypes:
    Description: List of valid choice types
    Type: CommaDelimitedList

  ValidSongIds:
    Description: List of valid song IDs
    Type: CommaDelimitedList


Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub ${Environment}-enchanted-brain-mturk
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: alias/aws/s3

  AppSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${Environment}/enchanted-brain/mturk/app-secret
      GenerateSecretString:
        PasswordLength: 32

  ChoiceWriter:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-enchanted-brain-mturk-choice-writer
      Runtime: nodejs12.x
      CodeUri: app/src/functions/choice-writer
      Handler: index.handler
      MemorySize: 128
      Timeout: 30
      AutoPublishAlias: live
      Environment:
        Variables:
          ENCHANTED_BRAIN_APP_SECRET_ARN: !Ref AppSecret
          ENCHANTED_BRAIN_S3_BUCKET_NAME: !Ref S3Bucket
          ENCHANTED_BRAIN_VALID_CHOICE_TYPES: !Join [',', !Ref ValidChoiceTypes]
          ENCHANTED_BRAIN_VALID_SONG_IDS: !Join [',', !Ref ValidSongIds]
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /Choices
            Method: POST
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: s3:PutObject
              Resource: !Sub ${S3Bucket.Arn}/*
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref AppSecret


Outputs:

  ServerlessRestApiId:
    Value: !Ref ServerlessRestApi

  ServerlessRestApiUrl:
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApi.Stage}
