AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Parameters:

  AdminUserPoolGroupName:
    Type: String

  CognitoUserPoolId:
    Type: String

  Environment:
    Type: String
    AllowedValues:
      - development
      - production
      - staging
      - testing

  EventName:
    Type: String


Mappings:

  ApiParams:
    ServerlessRestApi:
      StageName: Prod

  RouteKeys:
    ChoiceMade:
      Key: CHOICE_MADE
    Connect:
      Key: $connect
    Disconnect:
      Key: $disconnect
    EventStageChanged:
      Key: EVENT_STAGE_CHANGED


Globals:

  Function:
    Runtime: python3.7
    Handler: index.handler
    MemorySize: 128
    Timeout: 3
    AutoPublishAlias: live
    Environment:
      Variables:
        APP_ENVIRONMENT: !Ref Environment
        EVENT_NAME: !Ref EventName
        DYNAMODB_ENDPOINT: ''

Resources:

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${Environment}-enchanted-brain
      AttributeDefinitions:
        - AttributeName: recordType
          AttributeType: S
        - AttributeName: recordId
          AttributeType: S
      KeySchema:
        - AttributeName: recordType
          KeyType: HASH
        - AttributeName: recordId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      SSESpecification:
        SSEEnabled: True
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  Api:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub ${Environment}-enchanted-brain
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.event

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-enchanted-brain-authorizer
      CodeUri: app/src/functions/authorizer
      Environment:
        Variables:
          API_ARN: !Sub
            - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/${StageName}
            - StageName: !FindInMap [ApiParams,  ServerlessRestApi, StageName]
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          COGNITO_ADMIN_GROUP_NAME: !Ref AdminUserPoolGroupName

  AuthorizerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt AuthorizerFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*

  ApiAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      Name: !Sub ${Environment}-enchanted-brain
      ApiId: !Ref Api
      AuthorizerType: REQUEST
      AuthorizerUri: !Join
        - ''
        - - !Sub arn:aws:apigateway:${AWS::Region}:lambda:path
          - !Sub /2015-03-31/functions/${AuthorizerFunction.Arn}/invocations
      IdentitySource:
        - route.request.querystring.token

  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${Environment}-enchanted-brain
      ContentUri: app/src/layer
      CompatibleRuntimes:
        - python3.7

  CallbackSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${Environment}-enchanted-brain-callback-global
      KmsMasterKeyId: alias/aws/sns

  CallbackKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub ${Environment}-enchanted-brain-callback
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: kms:*
            Resource: '*'
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
          - Effect: Allow
            Action:
              - kms:GenerateDataKey*
              - kms:Decrypt
            Resource: '*'
            Principal:
              Service: sns.amazonaws.com

  CallbackKmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${Environment}/enchanted-brain/callback
      TargetKeyId: !Ref CallbackKmsKey

  CallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-enchanted-brain-callback
      CodeUri: app/src/functions/callback
      Layers:
        - !Ref LambdaLayer
      Environment:
        Variables:
          API_URL: !Sub
            - https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${StageName}
            - StageName: !FindInMap [ApiParams,  ServerlessRestApi, StageName]
      Policies:
        - SQSPollerPolicy:
            QueueName: !Sub ${Environment}-enchanted-brain-callback-*
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: execute-api:ManageConnections
              Resource: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*
            - Effect: Allow
              Action: kms:Decrypt
              Resource: !GetAtt CallbackKmsKey.Arn

  CallbackFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CallbackFunction.Alias
      Principal: sqs.amazonaws.com
      SourceArn: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${Environment}-enchanted-brain-callback-*

  PublisherFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-enchanted-brain-publisher
      CodeUri: app/src/functions/publisher
      Events:
        StreamEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt Table.StreamArn
            StartingPosition: TRIM_HORIZON
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt CallbackSnsTopic.TopicName

  OnConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-enchanted-brain-on-connect
      CodeUri: app/src/functions/on_connect
      Layers:
        - !Ref LambdaLayer
      Timeout: 10
      Environment:
        Variables:
          CALLBACK_FUNCTION_ARN: !Ref CallbackFunction.Alias
          CALLBACK_SNS_TOPIC_ARN: !Ref CallbackSnsTopic
          CALLBACK_SQS_QUEUE_ARN_PREFIX: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${Environment}-enchanted-brain-callback
          DYNAMODB_TABLE_NAME: !Ref Table
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: sqs:CreateQueue
              Resource: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${Environment}-enchanted-brain-callback-*
            - Effect: Allow
              Action: sns:Subscribe
              Resource: !Ref CallbackSnsTopic
              Condition:
                ForAnyValue:StringEquals:
                  sns:Protocol: sqs
                ForAnyValue:StringLike:
                  sns:Endpoint: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${Environment}-enchanted-brain-callback-*
            - Effect: Allow
              Action: lambda:CreateEventSourceMapping
              Resource: '*'
              Condition:
                ForAnyValue:ArnEquals:
                  lambda:FunctionArn: !Ref CallbackFunction.Alias

  OnConnectRoute:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cloudformation.ws-route.yml
      Parameters:
        ApiId: !Ref Api
        AuthorizerId: !Ref ApiAuthorizer
        CreateRouteResponse: 'yes'
        FunctionArn: !Ref OnConnectFunction.Alias
        RouteKey: !FindInMap [RouteKeys, Connect, Key]

  OnDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-enchanted-brain-on-disconnect
      CodeUri: app/src/functions/on_disconnect
      Layers:
        - !Ref LambdaLayer
      Timeout: 120
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref Table
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: sqs:DeleteQueue
              Resource: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${Environment}-enchanted-brain-callback-*
            - Effect: Allow
              Action: sns:Unsubscribe
              Resource: '*'
            - Effect: Allow
              Action: lambda:DeleteEventSourceMapping
              Resource: '*'
              Condition:
                ForAnyValue:ArnEquals:
                  lambda:FunctionArn: !Ref CallbackFunction.Alias

  OnDisconnectRoute:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cloudformation.ws-route.yml
      Parameters:
        ApiId: !Ref Api
        FunctionArn: !Ref OnDisconnectFunction.Alias
        RouteKey: !FindInMap [RouteKeys, Disconnect, Key]

  ChoiceMadeSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${Environment}-enchanted-brain-choice-made
      KmsMasterKeyId: alias/aws/sns

  OnChoiceMadeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-enchanted-brain-on-choice-made
      CodeUri: app/src/functions/on_choice_made
      Layers:
        - !Ref LambdaLayer
      Environment:
        Variables:
          CALLBACK_SNS_TOPIC_ARN: !Ref CallbackSnsTopic
          CHOICE_MADE_SNS_TOPIC_ARN: !Ref ChoiceMadeSnsTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ChoiceMadeSnsTopic.TopicName

  OnChoiceMadeRoute:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cloudformation.ws-route.yml
      Parameters:
        ApiId: !Ref Api
        CreateRouteResponse: 'yes'
        FunctionArn: !Ref OnChoiceMadeFunction.Alias
        RouteKey: !FindInMap [RouteKeys, ChoiceMade, Key]

  OnEventStageChangedFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-enchanted-brain-on-event-stage-changed
      CodeUri: app/src/functions/on_event_stage_changed
      Layers:
        - !Ref LambdaLayer
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref Table
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table

  OnEventStageChangedRoute:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cloudformation.ws-route.yml
      Parameters:
        ApiId: !Ref Api
        FunctionArn: !Ref OnEventStageChangedFunction.Alias
        RouteKey: !FindInMap [RouteKeys, EventStageChanged, Key]

  ApiDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - OnChoiceMadeFunctionAliaslive
      - OnChoiceMadeRoute
      - OnConnectFunctionAliaslive
      - OnConnectRoute
      - OnDisconnectFunctionAliaslive
      - OnDisconnectRoute
      - OnEventStageChangedFunctionAliaslive
      - OnEventStageChangedRoute
    Properties:
      ApiId: !Ref Api

  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref Api
      DeploymentId: !Ref ApiDeployment
      StageName: !FindInMap [ApiParams,  ServerlessRestApi, StageName]

  ChoiceWriterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-enchanted-brain-choice-writer
      CodeUri: app/src/functions/choice_writer
      Layers:
        - !Ref LambdaLayer
      Events:
        SnsEvent:
          Type: SNS
          Properties:
            Topic: !Ref ChoiceMadeSnsTopic
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref Table
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table


Outputs:

  TableName:
    Value: !Ref Table

  WebSocketURI:
    Value: !Sub wss://${Api}.execute-api.${AWS::Region}.amazonaws.com/${ApiStage}
