AWSTemplateFormatVersion: 2010-09-09

Parameters:

  ApiId:
    Type: String

  CreateRouteResponse:
    AllowedValues:
      - 'yes'
      - 'no'
    Default: 'no'

  FunctionArn:
    Type: String

  RouteKey:
    Type: String


Conditions:

  IsCreateRouteResponse: !Equals [!Ref CreateRouteResponse, 'yes']


Resources:

  Integration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiId
      Description: !Ref RouteKey
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations

  Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref FunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

  Route:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiId
      RouteKey: !Ref RouteKey
      AuthorizationType: NONE #TODO
      Target: !Sub integrations/${Integration}

  RouteResponse:
    Type: AWS::ApiGatewayV2::RouteResponse
    Condition: IsCreateRouteResponse
    Properties:
      ApiId: !Ref MyApi
      RouteId: !Ref Route
      RouteResponseKey: $default
