AWSTemplateFormatVersion: 2010-09-09

Parameters:

  ApiId:
    Type: String

  AuthorizerId:
    Type: String
    Default: ''

  CreateRouteResponse:
    Type: String
    AllowedValues:
      - 'yes'
      - 'no'
    Default: 'no'

  FunctionArn:
    Type: String

  RouteKey:
    Type: String


Conditions:

  IsAuthorized: !Not [!Equals [!Ref AuthorizerId, '']]

  IsCreateRouteResponse: !Equals [!Ref CreateRouteResponse, 'yes']


Resources:

  Integration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiId
      Description: !Ref RouteKey
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionArn}/invocations

  Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref FunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiId}/*

  Route:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiId
      RouteKey: !Ref RouteKey
      RouteResponseSelectionExpression: !If
        - IsCreateRouteResponse
        - $default
        - !Ref AWS::NoValue
      AuthorizationType: !If
        - IsAuthorized
        - CUSTOM
        - NONE
      AuthorizerId: !If
        - IsAuthorized
        - !Ref AuthorizerId
        - !Ref AWS::NoValue
      Target: !Sub integrations/${Integration}

  RouteResponse:
    Type: AWS::ApiGatewayV2::RouteResponse
    Condition: IsCreateRouteResponse
    Properties:
      ApiId: !Ref ApiId
      RouteId: !Ref Route
      RouteResponseKey: $default
