version: '3.5'

services:

  pipenv:
    image: sjawhar/pipenv:3.7-2018.11.26
    volumes:
      - ./app:/app
      - ./app/src/layer/python:/opt/python
      - ~/.local/share/virtualenvs:/home/pipenv/.local/share/virtualenvs
    environment:
      PYTHONPATH: /opt/python
    working_dir: /app
    user: pipenv
